from fastapi import APIRouter, Response
from datetime import datetime
import io
import csv
from ..database.repository import data_repository

router = APIRouter(prefix="/api/reports", tags=["Intelligence Reports"])

@router.get("/brief")
def get_executive_intelligence_brief():
    """Generates an AI-driven National Cybercrime Executive Intelligence Brief."""
    preds = data_repository.predictions
    critical_preds = [p for p in preds if p["risk_score"] >= 85]
    total_exposure = sum(p["estimated_exposure"] for p in preds)
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    hotspots_summary = []
    for p in critical_preds[:4]:
        hotspots_summary.append({
            "name": p["name"],
            "location": f"{p['locality']}, {p['district']}",
            "risk_score": p["risk_score"],
            "risk_level": p["risk_level"],
            "forecast_window": p["forecast_window"],
            "exposure_lakhs": p["estimated_exposure"],
            "primary_crime": p["primary_crime_category"]
        })

    brief = {
        "report_id": f"INTEL-BRIEF-{datetime.now().strftime('%Y%m%d')}-01",
        "title": "National Cybercrime Cashout Risk & Predictive Hotspot Intelligence Brief",
        "classification": "RESTRICTED // LAW ENFORCEMENT & BANKING NODAL AUTHORITIES",
        "generated_at": now_str,
        "executive_summary": (
            f"As of {now_str}, the AI Predictive Engine has flagged {len(critical_preds)} critical withdrawal zones "
            f"across primary cybercrime corridors with an aggregate potential exposure of ₹{total_exposure / 100.0:.2f} Crores. "
            f"The primary emerging pattern indicates high-velocity UPI and Investment Fraud funds transitioning into Layer-2 mule "
            f"accounts with high-probability cash extraction concentrated in the 19:00–23:00 evening window."
        ),
        "primary_threat_cluster": critical_preds[0] if critical_preds else None,
        "critical_hotspots": hotspots_summary,
        "recommended_strategic_actions": [
            "Issue immediate geofenced withdrawal hold alerts to participating banks across flagged ATM clusters.",
            "Deploy local LEA Quick Response Teams (QRT) for active surveillance around identified ATM terminals.",
            "Enforce automated 1930 NCRP beneficiary blocking via Citizen Financial Cyber Fraud Reporting System.",
            "Prioritize joint inter-state intelligence sharing between Odisha CID, Haryana Cyber Command, and Delhi IFSO."
        ],
        "disclaimer": "Generated by CYBERPREDICT Demonstration System. All datasets are synthetic and designed for prototype evaluation."
    }
    return {"status": "success", "report": brief}

@router.get("/export/csv")
def export_hotspots_csv():
    """Exports predicted hotspots to CSV for field commanders and analysts."""
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Header
    writer.writerow([
        "Hotspot ID", "Cluster Name", "State", "District", "Locality",
        "Risk Score", "Risk Level", "Probability", "Forecast Window",
        "Estimated Exposure (Lakhs)", "Nearby ATMs", "Linked Complaints", "Primary Crime"
    ])

    for p in data_repository.predictions:
        writer.writerow([
            p["id"], p["name"], p["state"], p["district"], p["locality"],
            p["risk_score"], p["risk_level"], p["prediction_probability"], p["forecast_window"],
            p["estimated_exposure"], p["nearby_atms_count"], p["linked_complaints_count"], p["primary_crime_category"]
        ])

    csv_data = output.getvalue()
    return Response(
        content=csv_data,
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=cyberpredict_hotspots_{datetime.now().strftime('%Y%m%d')}.csv"}
    )
